In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

* **Load the dataset from “sampleData.csv”.  Create training and test datasets using random splitting (70-30)%. Print the train and test data. Create a linear regression model and report the model performance. (The last feature is the target variable)**

In [4]:
#Load data
df = pd.read_csv('sample_dataset.csv')

In [5]:
df.head()

,Subject ID,sample ID,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31
0,1,1,0.049592,0.545805,0.771077,0.387171,0.618290,0.869132,0.139296,0.454377,...,0.118728,0.971647,0.517703,0.390375,0.364423,0.948268,0.921592,0.986265,0.983804,0.892498
1,1,2,0.784486,0.361281,0.681752,0.494981,0.490758,0.132277,0.475217,0.041860,...,0.836944,0.694952,0.990620,0.573024,0.627210,0.670506,0.339624,0.238391,0.141122,0.989782
2,1,3,0.017367,0.661350,0.849570,0.833185,0.591147,0.357999,0.583466,0.681106,...,0.006386,0.937494,0.343176,0.816586,0.295563,0.078583,0.724032,0.847065,0.704773,0.793935
3,1,4,0.197825,0.227258,0.177861,0.179123,0.397492,0.010650,0.111507,0.719310,...,0.177616,0.517563,0.336766,0.315501,0.478920,0.203019,0.190466,0.739788,0.210447,0.084941
4,1,5,0.899094,0.817947,0.889295,0.205932,0.005874,0.687918,0.874622,0.523576,...,0.921892,0.784476,0.778715,0.517458,0.289470,0.185447,0.960247,0.746802,0.891682,0.733321

In [6]:
#get the size of the dataset
df.shape

(150, 34)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Subject ID  150 non-null    int64
 1   sample ID   150 non-null    int64
 2   feature_0   150 non-null    float64
 3   feature_1   150 non-null    float64
 4   feature_2   150 non-null    float64
 5   feature_3   150 non-null    float64
 6   feature_4   150 non-null    float64
 7   feature_5   150 non-null    float64
 8   feature_6   150 non-null    float64
 9   feature_7   150 non-null    float64
 10  feature_8   150 non-null    float64
 11  feature_9   150 non-null    float64
 12  feature_10  150 non-null    float64
 13  feature_11  150 non-null    float64
 14  feature_12  150 non-null    float64
 15  feature_13  150 non-null    float64
 16  feature_14  150 non-null    float64
 17  feature_15  150 non-null    float64
 18  feature_16  150 non-null    float64
 19  feature_17  150 non-null    float64
 20  feature_18  150 non-null    float64
 21  feature_19  150 non-null    float64
 22  feature_20  150 non-null    float64
 23  feature_21  150 non-null    float64
 24  feature_22  150 non-null    float64
 25  feature_23  150 non-null    float64
 26  feature_24  150 non-null    float64
 27  feature_25  150 non-null    float64
 28  feature_26  150 non-null    float64
 29  feature_27  150 non-null    float64
 30  feature_28  150 non-null    float64
 31  feature_29  150 non-null    float64
 32  feature_30  150 non-null    float64
 33  feature_31  150 non-null    float64
dtypes: float64(32), int64(2)
memory usage: 40.0 KB

In [8]:
df.describe()

,Subject ID,sample ID,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,15.500000,3.000000,0.519458,0.515589,0.551360,0.518398,0.507698,0.477344,0.478999,0.501294,...,0.520925,0.541186,0.507834,0.512649,0.475324,0.534528,0.494043,0.553169,0.479062,0.495994
std,8.684438,1.418951,0.293991,0.285416,0.270573,0.281292,0.285513,0.282899,0.281569,0.270244,...,0.300841,0.284148,0.293735,0.287857,0.306199,0.300744,0.287329,0.277459,0.300696,0.309316
min,1.000000,1.000000,0.007503,0.001806,0.010256,0.013015,0.005874,0.004173,0.000843,0.009966,...,0.002228,0.005880,0.004842,0.005909,0.001088,0.000308,0.008065,0.006614,0.000409,0.004522
25%,8.000000,2.000000,0.238741,0.268906,0.345227,0.269774,0.261920,0.256708,0.269379,0.282559,...,0.259045,0.296334,0.263791,0.256659,0.194541,0.288860,0.259479,0.326223,0.190981,0.222037
50%,15.500000,3.000000,0.580427,0.519306,0.594042,0.513395,0.524667,0.475332,0.454109,0.516709,...,0.522819,0.544364,0.496645,0.534315,0.467230,0.577002,0.476170,0.538039,0.510464,0.495930
75%,23.000000,4.000000,0.770542,0.769700,0.787061,0.750345,0.761900,0.686078,0.723747,0.720259,...,0.826411,0.786015,0.768850,0.755917,0.765318,0.804632,0.728498,0.805034,0.706531,0.747992
max,30.000000,5.000000,0.998945,0.996198,0.994709,0.996611,0.999945,0.991820,0.989347,0.973196,...,0.999487,0.999388,0.990620,0.995900,0.994541,0.998447,0.990492,0.992272,0.999007,0.989782

In [9]:
df.isnull().sum()

Subject ID    0
sample ID     0
feature_0     0
feature_1     0
feature_2     0
feature_3     0
feature_4     0
feature_5     0
feature_6     0
feature_7     0
feature_8     0
feature_9     0
feature_10    0
feature_11    0
feature_12    0
feature_13    0
feature_14    0
feature_15    0
feature_16    0
feature_17    0
feature_18    0
feature_19    0
feature_20    0
feature_21    0
feature_22    0
feature_23    0
feature_24    0
feature_25    0
feature_26    0
feature_27    0
feature_28    0
feature_29    0
feature_30    0
feature_31    0
dtype: int64

In [10]:
#Get the features and labels
X = df.iloc[:,:-1]
y = df.iloc[:, -1]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
#Split train and test dataset 7:3
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
#Print the train and test set
X_train.head()

,Subject ID,sample ID,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30
81,17,2,0.965936,0.878103,0.386270,0.218148,0.999945,0.987537,0.633259,0.067809,...,0.527833,0.671222,0.552047,0.668078,0.439723,0.485720,0.124052,0.667793,0.992199,0.157581
133,27,4,0.378926,0.822470,0.810673,0.796805,0.799147,0.493268,0.473827,0.855313,...,0.687249,0.297938,0.288673,0.078337,0.762598,0.206676,0.013747,0.909569,0.192709,0.049537
137,28,3,0.602190,0.836786,0.739193,0.074982,0.321208,0.352287,0.963184,0.189590,...,0.794904,0.617638,0.762673,0.614363,0.018864,0.269345,0.190072,0.258485,0.169470,0.870730
75,16,1,0.647087,0.583075,0.240903,0.686149,0.032975,0.141510,0.174590,0.020943,...,0.030765,0.441087,0.632321,0.046242,0.282524,0.895349,0.043557,0.970534,0.267381,0.010865
109,22,5,0.299556,0.944794,0.245175,0.153634,0.134723,0.196001,0.702827,0.628675,...,0.629802,0.251942,0.594300,0.306838,0.766697,0.016570,0.510205,0.540352,0.267505,0.856083

In [14]:
y_train.head()

81     0.664231
133    0.696368
137    0.242381
75     0.628457
109    0.970861
Name: feature_31, dtype: float64

In [15]:
X_test.head()

,Subject ID,sample ID,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30
73,15,4,0.948736,0.701764,0.758984,0.764294,0.302214,0.316796,0.133772,0.972011,...,0.558057,0.373930,0.760234,0.495353,0.619501,0.815067,0.746257,0.952560,0.765208,0.001485
18,4,4,0.153687,0.691285,0.620214,0.268056,0.730510,0.441093,0.817469,0.592335,...,0.118995,0.471973,0.783188,0.916690,0.991552,0.932083,0.032833,0.561273,0.446163,0.150041
118,24,4,0.905840,0.408101,0.541389,0.341156,0.297925,0.484835,0.182228,0.225059,...,0.227989,0.397496,0.645922,0.379403,0.461324,0.834726,0.500437,0.058176,0.755119,0.033973
78,16,4,0.587969,0.612320,0.688419,0.298370,0.528624,0.252250,0.110105,0.860619,...,0.777804,0.999487,0.942200,0.717267,0.927554,0.830067,0.188607,0.176468,0.358316,0.416079
76,16,2,0.085164,0.364504,0.698854,0.740021,0.512721,0.834822,0.712927,0.849809,...,0.021494,0.357855,0.449751,0.100079,0.835015,0.485891,0.589269,0.357913,0.802182,0.160600

In [16]:
y_test.head()

73     0.036916
18     0.515118
118    0.748968
78     0.903448
76     0.917985
Name: feature_31, dtype: float64

In [17]:
#Build linear model
from sklearn.linear_model import LinearRegression

In [18]:
lr = LinearRegression()

In [19]:
lr.fit(X_train, y_train)

LinearRegression()

In [20]:
pred = lr.predict(X_test)

In [21]:
#Validate the model
from sklearn.metrics import mean_squared_error, mean_absolute_error, confusion_matrix, classification_report

In [22]:
print('Mean Square Error: ', round(mean_squared_error(y_test, pred),2))
print('Mean Absolute Error: ', round(mean_absolute_error(y_test, pred),2))
print('Classification report: ', classification_report(y_test.round(), pred.round()))

Mean Square Error:  0.12
Mean Absolute Error:  0.3
Classification report:                precision    recall  f1-score   support

         0.0       0.50      0.57      0.53        21
         1.0       0.57      0.50      0.53        24

    accuracy                           0.53        45
   macro avg       0.54      0.54      0.53        45
weighted avg       0.54      0.53      0.53        45

* **Create training and test dataset using leave-one-out based on Subject ID. Print the train and test dataset for the first iteration only.  Create a linear regression model and compare the performance with Q-1. Explain your findings.**

In [28]:
from sklearn.model_selection import cross_val_score, LeaveOneOut, LeaveOneGroupOut

In [29]:
X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values

In [30]:
logo = LeaveOneGroupOut()

In [32]:
groups = df['Subject ID']

y_true, y_pred = list(), list()

for i, (train_index, test_index) in enumerate(logo.split(X, y, groups)):
    
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    if i == 1:
        print('X_train: ', X_train)
        print('X_test: ', X_test)
        print('y_train: ', y_train)
        print('y_test: ', y_test)
        
    lr_model = LinearRegression()
    lr_model.fit(X_train, y_train)
    
    predict = lr_model.predict(X_test)
    
    y_true.append(y_test[0])
    y_pred.append(predict[0])
    
print('Mean Square Error: ', round(mean_squared_error(y_true, y_pred),2))
print('Mean Absolute Error: ', round(mean_absolute_error(y_true, y_pred),2))
print('Classification report: ', classification_report(np.around(np.array(y_true)), np.around(np.array(y_pred))))

X_train:  [[1.00000000e+00 1.00000000e+00 4.95920928e-02 ... 9.21592123e-01
  9.86265245e-01 9.83803733e-01]
 [1.00000000e+00 2.00000000e+00 7.84486332e-01 ... 3.39623796e-01
  2.38391490e-01 1.41121801e-01]
 [1.00000000e+00 3.00000000e+00 1.73669900e-02 ... 7.24031975e-01
  8.47064837e-01 7.04772812e-01]
 ...
 [3.00000000e+01 3.00000000e+00 7.31092685e-01 ... 6.52748112e-01
  2.60084704e-01 4.19321041e-01]
 [3.00000000e+01 4.00000000e+00 2.83677687e-01 ... 2.25610011e-02
  8.07065153e-01 7.95217481e-01]
 [3.00000000e+01 5.00000000e+00 7.00753702e-01 ... 7.28635928e-01
  9.92271704e-01 5.05454738e-01]]
X_test:  [[2.         1.         0.16878321 0.42827873 0.54215273 0.45705544
  0.38854539 0.54591027 0.95060005 0.0627298  0.68175111 0.59199996
  0.09369669 0.19995852 0.56439894 0.43724959 0.74318467 0.36635595
  0.77789614 0.281484   0.75807968 0.18023986 0.01097322 0.19509284
  0.90835907 0.94590834 0.84126831 0.46272227 0.19416378 0.85619543
  0.39953687 0.80800952 0.83870045]
 [2.         2.         0.64339153 0.94785601 0.70166308 0.08586965
  0.82567341 0.21563627 0.35053351 0.39809926 0.13484064 0.62029124
  0.8149553  0.58641493 0.30027834 0.24318983 0.25360032 0.78996646
  0.69429888 0.42824844 0.58041354 0.46860306 0.64525518 0.6799212
  0.88636368 0.59651302 0.17286104 0.54361628 0.10592115 0.29420246
  0.8714819  0.49302178 0.12377465]
 [2.         3.         0.47788635 0.81045292 0.13106891 0.99661056
  0.6839755  0.65607485 0.78749832 0.42532329 0.7097009  0.16680114
  0.46507754 0.8571741  0.06136563 0.21061275 0.24635732 0.8733667
  0.92834403 0.92559056 0.47495909 0.46892707 0.76954735 0.49210197
  0.84875992 0.52387598 0.18533771 0.53452235 0.73108896 0.06720344
  0.21222985 0.93414429 0.19018005]
 [2.         4.         0.59275033 0.70124053 0.16545181 0.43917375
  0.18290999 0.96556428 0.05504353 0.84624944 0.83886025 0.10567812
  0.33319416 0.21757954 0.84942501 0.68479361 0.40713526 0.07723629
  0.55008933 0.79969572 0.03101139 0.72431315 0.61507025 0.20330316
  0.58796218 0.61447225 0.70106873 0.79703479 0.73452178 0.62994386
  0.03755617 0.88627685 0.00690722]
 [2.         5.         0.76431375 0.52318535 0.8199947  0.73033063
  0.67162158 0.05624517 0.63036822 0.62157002 0.36713458 0.69684487
  0.77222784 0.20788472 0.86741594 0.33447244 0.73580231 0.98556318
  0.64336986 0.73888369 0.05154488 0.9171865  0.11382578 0.91319323
  0.89255392 0.93206862 0.61108748 0.92079605 0.26625528 0.2651787
  0.55274113 0.00661354 0.3714067 ]]
y_train:  [0.89249786 0.98978179 0.79393521 0.08494061 0.73332096 0.46880982
 0.07395554 0.83470287 0.69594448 0.11035386 0.66196294 0.62269809
 0.10122979 0.51511762 0.49742597 0.48999149 0.0514743  0.88388184
 0.36938713 0.05301557 0.00452228 0.11999208 0.70416513 0.04075818
 0.43907458 0.20162267 0.54732458 0.50371693 0.92919793 0.00906898
 0.54302797 0.88575816 0.97377358 0.3635207  0.02057692 0.91451612
 0.04745439 0.92831739 0.17773638 0.03016595 0.35713024 0.49241214
 0.9427441  0.57359677 0.78089927 0.24561857 0.90455813 0.86800852
 0.42198075 0.41342621 0.13190751 0.41990721 0.36912586 0.76029264
 0.33263073 0.66574987 0.00802404 0.52644837 0.89092334 0.091392
 0.48009456 0.27058464 0.22519468 0.19067069 0.52142003 0.38217262
 0.97695479 0.22098475 0.03691582 0.07296584 0.62845712 0.91798496
 0.27742733 0.90344849 0.84651846 0.10339458 0.66423053 0.45681313
 0.47918227 0.11754403 0.98868171 0.10561804 0.78088714 0.74015368
 0.70573831 0.51261064 0.57752406 0.94086586 0.50553008 0.65215918
 0.49436291 0.48400131 0.88081578 0.70138312 0.97172632 0.01259635
 0.33877672 0.78092383 0.94917577 0.74766376 0.2415232  0.55356904
 0.73778801 0.03228583 0.97086052 0.23494446 0.83383715 0.13989233
 0.3243831  0.94759108 0.66470743 0.8552364  0.49443313 0.74896784
 0.26151037 0.4763913  0.41733295 0.17301678 0.16907323 0.23169174
 0.40782318 0.14138606 0.0070237  0.68661365 0.18450147 0.69154291
 0.19729634 0.2619361  0.6963678  0.09307543 0.55889954 0.58525822
 0.24238115 0.07205571 0.91801434 0.2442154  0.61902254 0.94444096
 0.10757813 0.69045053 0.70159984 0.96718256 0.90773587 0.44741334
 0.94373157]
y_test:  [0.74256413 0.74810187 0.07496672 0.22983014 0.62735204]
Mean Square Error:  0.1
Mean Absolute Error:  0.26
Classification report:                precision    recall  f1-score   support

         0.0       0.47      0.41      0.44        17
         1.0       0.33      0.38      0.36        13

    accuracy                           0.40        30
   macro avg       0.40      0.40      0.40        30
weighted avg       0.41      0.40      0.40        30

As we can see that all the metrics from the train test split and the leave one group out method are pretty the same: mean square error is around 0.12, mean absolute error is 0.3, accuracy is around 50%.